### ISSUE TITLE
Crash on insert()

### ISSUE THREAD

**Issue by gkorland** [rust-lang/hashbrown#143] opened 2020-02-10 10:43 UTC
```
___lldb_unnamed_symbol1$$libpthread.so.0 (@__restore_rt:3)
_mm_load_si128 (@core::core_arch::x86::sse2::_mm_load_si128::h31ad0ac98cca243e:7)
load_aligned (@hashbrown::raw::sse2::Group::load_aligned::h07726ae12d146f0a:13)
new<(*const serde_json::value::Value, ())> (@hashbrown::raw::RawIterRange$LT$T$GT$::new::h315ac80c6dd69c8c:18)
iter<(*const serde_json::value::Value, ())> (@hashbrown::raw::RawTable$LT$T$GT$::iter::he64f03d3a2e7376b:32)
resize<(*const serde_json::value::Value, ()),closure-1> (@hashbrown::raw::RawTable$LT$T$GT$::resize::h150c3f3ba9377904:125)
reserve_rehash<(*const serde_json::value::Value, ()),closure-1> (@hashbrown::raw::RawTable$LT$T$GT$::reserve_rehash::h57be3f64f169106b:111)
reserve<(*const serde_json::value::Value, ()),closure-1> (@hashbrown::raw::RawTable$LT$T$GT$::reserve::h49982cfae6135115:23)
insert<(*const serde_json::value::Value, ()),closure-1> (@hashbrown::raw::RawTable$LT$T$GT$::insert::h1fd330f9eb644a76:69)
insert<*const serde_json::value::Value,(),std::collections::hash::map::RandomState> (@hashbrown::map::HashMap$LT$K$C$V$C$S$GT$::insert::h389f0db0a85a5c9d:62)
insert<*const serde_json::value::Value,(),std::collections::hash::map::RandomState> (@std::collections::hash::map::HashMap$LT$K$C$V$C$S$GT$::insert::hc8ac2a757d3d118a:10)
insert<*const serde_json::value::Value,std::collections::hash::map::RandomState> (@std::collections::hash::set::HashSet$LT$T$C$S$GT$::insert::h39fb5ee15d35a1ef:10)
```

**Comment by Amanieu** [comment] 2020-02-10 10:44
Are you using a custom allocator which doesn't respect alignment constraints?

**Comment by gkorland** [comment] 2020-02-10 10:50
Yes, I'm using Redis allocator, which is using jemalloc

**Comment by Amanieu** [comment] 2020-02-10 10:59
The allocator is buggy: hashbrown requests 16-byte aligned memory in its `Layout`, but it seems that the Redis allocator ignores the alignment part of the `Layout`. I am closing this since this is not a bug in hashbrown.

**Closed by Amanieu** 2020-02-10 10:59 UTC

**Comment by gkorland** [comment] 2020-02-10 14:13
@Amanieu Thanks! it you were right, we ignored the `layout.align()` in our GlobalAlloc implementation.
Thanks for the great hint!
